;;; mejelly-theme.el --- Mejelly theme for GNU Emacs 24 (deftheme)

;; Author: Aldric Giacomoni <trevoke@gmail.com>
;; Original color-theme author: Mark Tran <mark.tran@gmail.com>
;; URL: http://github.com/trevoke/color-theme-mejelly
;; Version: 1.0.40

;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.
(deftheme mejelly "The mejelly color theme")

(let ((class '((class color) (min-colors 89)))
      (mejelly-fg "#e8e8d4")
      (mejelly-bg "#151515")
      (mejelly-blue-0 "#467898")
      (mejelly-green-0 "#556536")
      (mejelly-green-1 "#7798d4")
      (mejelly-green-2 "#99ac6d")
      (mejelly-grey-0 "#888888")
      (mejelly-grey-1 "#7f7f7f")
      (mejelly-grey-2 "#151515")
      (mejelly-grey-3 "#1c1c1c")
      (mejelly-grey-4 "#363636")
      (mejelly-orange-0 "#ffb964")
      (mejelly-purple-0 "#c6b8fc")
      (mejelly-purple-1 "#474e90")
      (mejelly-purple-2 "#cd00cd")
      (mejelly-purple-3 "#540063")
      (mejelly-purple-4 "#a40073")
      (mejelly-red-0 "#cf6a4c")
      (mejelly-red-1 "#dd0093")
      (mejelly-red-2 "#de5577")
      (mejelly-red-3 "#ff73fd")
      (mejelly-yellow-0 "#fad07a")
      (mejelly-yellow-1 "#ffff00"))

      (custom-theme-set-faces
       'mejelly
       `(default ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(compilation-error ((,class (:foreground ,mejelly-red-0))))
       `(compilation-info ((,class (:foreground ,mejelly-yellow-0))))
       `(compilation-line-number ((,class (:foreground ,mejelly-grey-0))))
       `(compilation-mode-line-exit ((,class (:foreground ,mejelly-green-0))))
       `(compilation-mode-line-fail ((,class (:foreground ,mejelly-red-0))))
       `(compilation-mode-line-run ((,class (:foreground ,mejelly-yellow-0))))
       `(diredp-date-time ((,class (:foreground ,mejelly-fg))))
       `(diredp-deletion ((,class (:foreground ,mejelly-red-0))))
       `(diredp-dir-heading ((,class (:foreground ,mejelly-yellow-0 :background ,mejelly-bg))))
       `(diredp-dir-priv ((,class (:foreground ,mejelly-green-2 :background ,mejelly-bg))))
       `(diredp-exec-priv ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(diredp-file-name ((,class (:foreground ,mejelly-fg))))
       `(diredp-file-suffix ((,class (:foreground ,mejelly-fg))))
       `(diredp-link-priv ((,class (:foreground ,mejelly-fg))))
       `(diredp-number ((,class (:foreground ,mejelly-fg))))
       `(diredp-no-priv ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(diredp-rare-priv ((,class (:foreground ,mejelly-red-0 :background ,mejelly-bg))))
       `(diredp-read-priv ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(diredp-symlink ((,class (:foreground ,mejelly-red-3))))
       `(diredp-write-priv ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(emmet-preview-output ((,class (:background ,mejelly-purple-1))))
       `(erc-notice-face ((,class (:foreground ,mejelly-yellow-0))))
       `(erc-prompt-face ((,class (:foreground ,mejelly-fg))))
       `(erc-timestamp-face ((,class (:foreground ,mejelly-purple-0))))
       `(eshell-prompt ((,class (:foreground ,mejelly-red-0))))
       `(eshell-ls-directory ((,class (:weight normal :foreground ,mejelly-green-2))))
       `(eshell-ls-executable ((,class (:foreground ,mejelly-red-0))))
       `(eshell-ls-product ((,class (:foreground ,mejelly-fg))))
       `(eshell-ls-symlink ((,class (:foreground ,mejelly-purple-2))))
       `(font-lock-builtin-face ((,class (:foreground ,mejelly-blue-0))))
       `(font-lock-comment-face ((,class (:slant italic :foreground ,mejelly-grey-0))))
       `(font-lock-constant-face ((,class (:foreground ,mejelly-green-1))))
       `(font-lock-doc-face ((,class (:foreground ,mejelly-green-0))))
       `(font-lock-function-name-face ((,class (:foreground ,mejelly-yellow-0))))
       `(font-lock-keyword-face ((,class (:foreground ,mejelly-green-1))))
       `(font-lock-preprocessor-face ((,class (:foreground ,mejelly-fg))))
       `(font-lock-string-face ((,class (:foreground ,mejelly-green-2))))
       `(font-lock-type-face ((,class (:foreground ,mejelly-orange-0))))
       `(font-lock-variable-name-face ((,class (:foreground ,mejelly-purple-0))))
       `(font-lock-warning-face ((,class (:foreground ,mejelly-red-1))))
       `(enh-ruby-op-face ((,class (:foreground ,mejelly-fg))))
       `(enh-ruby-string-delimiter-face ((,class (:foreground ,mejelly-green-0))))
       `(git-commit-comment-file-face ((,class (:foreground ,mejelly-fg))))
       `(git-commit-comment-heading-face ((,class (:foreground ,mejelly-yellow-0))))
       `(git-commit-summary-face ((,class (:foreground ,mejelly-fg))))
       `(header-line ((,class (:foreground ,mejelly-fg))))
       `(helm-buffer-size ((,class (:foreground ,mejelly-fg))))
       `(helm-candidate-number ((,class (:foreground ,mejelly-fg :background ,mejelly-bg))))
       `(helm-ff-directory ((,class (:background ,mejelly-bg))))
       `(helm-ff-file ((,class (:foreground ,mejelly-fg))))
       `(helm-match ((,class (:foreground ,mejelly-yellow-0 :background ,mejelly-bg))))
       `(helm-selection ((,class (:background ,mejelly-purple-1))))
       `(helm-source-header ((,class (:foreground ,mejelly-red-1 :background ,mejelly-grey-4))))
       `(hl-line ((,class (:background ,mejelly-grey-4))))
       `(isearch ((,class (:foreground ,mejelly-fg :background ,mejelly-red-1))))
       `(isearch-fail ((,class (:background ,mejelly-red-1))))
       `(ido-first-match ((,class (:foreground ,mejelly-yellow-0))))
       `(ido-only-match ((,class (:foreground ,mejelly-green-0))))
       `(ido-subdir ((,class (:foreground ,mejelly-fg))))
       `(ido-virtual ((,class (:foreground ,mejelly-purple-0))))
       `(lazy-highlight ((,class (:foreground ,mejelly-red-1 :background nil))))
       `(linum ((,class (:slant italic :foreground ,mejelly-grey-4))))
       `(magit-branch ((,class (:foreground ,mejelly-red-0))))
       `(magit-diff-add ((,class (:foreground ,mejelly-green-0 :background ,mejelly-bg))))
       `(magit-diff-del ((,class (:foreground ,mejelly-red-0 :background ,mejelly-bg))))
       `(magit-diff-file-header ((,class (:inherit nil :foreground ,mejelly-red-2))))
       `(magit-diff-hunk-header ((,class (:inherit nil :foreground ,mejelly-yellow-0))))
       `(magit-item-highlight ((,class (:weight normal :background ,mejelly-grey-2))))
       `(magit-log-author ((,class (:foreground ,mejelly-fg))))
       `(magit-log-sha1 ((,class (:foreground ,mejelly-red-0))))
       `(magit-log-head-label-local ((,class (:foreground ,mejelly-fg))))
       `(magit-whitespace-warning-face ((,class (:background ,mejelly-red-1))))
       `(minibuffer-prompt ((,class (:foreground ,mejelly-fg))))
       `(mode-line ((,class (:foreground ,mejelly-fg :background nil))))
       `(mode-line-inactive ((,class (:foreground ,mejelly-grey-4 :background nil))))
       `(org-checkbox ((,class (:foreground ,mejelly-green-0))))
       `(org-date ((,class (:foreground ,mejelly-purple-0))))
       `(org-done ((,class (:foreground ,mejelly-green-0))))
       `(org-level-1 ((,class (:foreground ,mejelly-red-2))))
       `(org-level-2 ((,class (:foreground ,mejelly-red-0))))
       `(org-level-3 ((,class (:foreground ,mejelly-red-0))))
       `(org-special-keyword ((,class (:foreground ,mejelly-purple-0))))
       `(org-todo ((,class (:foreground ,mejelly-yellow-0))))
       `(region ((,class (:background ,mejelly-purple-1))))
       `(smerge-markers ((,class (:foreground ,mejelly-yellow-0 :background ,mejelly-grey-2))))
       `(smerge-refined-change ((,class (:foreground ,mejelly-green-0))))
       `(trailing-whitespace ((,class (:background ,mejelly-red-1))))
       `(web-mode-builtin-face ((,class (:foreground ,mejelly-blue-0))))
       `(web-mode-html-attr-name-face ((,class (:foreground ,mejelly-purple-0))))
       `(web-mode-html-tag-face ((,class (:foreground ,mejelly-fg))))
       `(web-mode-symbol-face ((,class (:foreground ,mejelly-green-1))))
       `(whitespace-trailing ((,class (:background ,mejelly-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'mejelly)

;;; mejelly-theme.el ends here
